/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Inventario;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhon
 */
public class AdmInventarioListView extends javax.swing.JFrame {
    DefaultTableModel modelTable = new DefaultTableModel();
    /**
     * Creates new form Principal
     */
    public AdmInventarioListView() {
        initComponents();
        
        this.JTableInven.setModel(modelTable);
        
        modelTable.addColumn("Codigo Material");
        modelTable.addColumn("Nombre");
        modelTable.addColumn("Descripcion");
        modelTable.addColumn("Cantidad Exist");
    }
    
    public void mostrarDatos(ArrayList<Inventario> models){
            if(modelTable.getRowCount() > 0){
                
            }
        for (Inventario model:models) {
            String[] data = {
                model.getId()+"",
                model.getNombre_Mp(),
                model.getDescrip_Mp(),
                model.getCant_Exist_Mp()
            };
            modelTable.addRow(data);
        }
    }
    public void deleteClientActionListener(ActionListener listener) {
        //this.btnEliminar.addActionListener(listener);
    }
    
    public int getSelectedClient(){
        return this.JTableInven.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JButtonAddMat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTableInven = new javax.swing.JTable();
        JButtonEliMat = new javax.swing.JButton();
        JButtonExportar = new javax.swing.JButton();
        JButtonModMat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuInicio = new javax.swing.JMenu();
        JMenuEmpleado = new javax.swing.JMenu();
        JMenuInventario = new javax.swing.JMenu();
        JMenuVentas = new javax.swing.JMenu();
        JMenuAyuda = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("INVENTARIO");

        JButtonAddMat.setBackground(new java.awt.Color(102, 255, 0));
        JButtonAddMat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JButtonAddMat.setText("Agregar Material");
        JButtonAddMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddMatActionPerformed(evt);
            }
        });

        JTableInven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Material", "Código", "Cantidad Paquete", "Precio Unidad"
            }
        ));
        jScrollPane3.setViewportView(JTableInven);

        JButtonEliMat.setBackground(new java.awt.Color(255, 51, 51));
        JButtonEliMat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JButtonEliMat.setText("Eliminar Material");
        JButtonEliMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEliMatActionPerformed(evt);
            }
        });

        JButtonExportar.setBackground(new java.awt.Color(255, 204, 0));
        JButtonExportar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JButtonExportar.setText("Exportar");
        JButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonExportarActionPerformed(evt);
            }
        });

        JButtonModMat.setBackground(new java.awt.Color(0, 204, 255));
        JButtonModMat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JButtonModMat.setText("Modificar Material");
        JButtonModMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonModMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(JButtonAddMat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonModMat)
                            .addGap(45, 45, 45)
                            .addComponent(JButtonEliMat)
                            .addGap(51, 51, 51)
                            .addComponent(JButtonExportar))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonAddMat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonModMat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonEliMat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        JMenuInicio.setText("INICIO");
        JMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMenuInicio);

        JMenuEmpleado.setText("NOMINA");
        jMenuBar1.add(JMenuEmpleado);

        JMenuInventario.setText("INVENTARIO");
        jMenuBar1.add(JMenuInventario);

        JMenuVentas.setText("VENTAS");
        jMenuBar1.add(JMenuVentas);

        JMenuAyuda.setText("AYUDA");
        jMenuBar1.add(JMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonAddMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddMatActionPerformed
        
    }//GEN-LAST:event_JButtonAddMatActionPerformed

    private void JButtonEliMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEliMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonEliMatActionPerformed

    private void JButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonExportarActionPerformed

    private void JButtonModMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonModMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonModMatActionPerformed

    private void JMenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuInicioMouseClicked
        //PRINCIPAL
        //JMenuInicio.addActionListener();
    }//GEN-LAST:event_JMenuInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmInventarioListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmInventarioListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmInventarioListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmInventarioListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmInventarioListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAddMat;
    private javax.swing.JButton JButtonEliMat;
    private javax.swing.JButton JButtonExportar;
    private javax.swing.JButton JButtonModMat;
    public static javax.swing.JMenu JMenuAyuda;
    public static javax.swing.JMenu JMenuEmpleado;
    public static javax.swing.JMenu JMenuInicio;
    public static javax.swing.JMenu JMenuInventario;
    public static javax.swing.JMenu JMenuVentas;
    private javax.swing.JTable JTableInven;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
